export default {
	BlockchainBlocks:'BlockList',
	BlockchainBlocksBlockDetails:'Block Details',
	BlockchainTransactions:'Transaction List',
	BlockchainTransactionsTransactionDetails:'TransactionDetails',
	StakingValidators:'ValidatorList',
	StakingValidatorsValidatorDetails:'Validator Details',
	StakingDelegationTxs:'DelegationTxsList',
	StakingValidationTxs:'ValidationTxsList',
	Transfer:'TransferList',
	AssetNativeAsset:'Native Asset List',
	AssetNativeAssetTxs:'Native Asset Txs List',
	GovParameters:'Parameter List',
	GovProposals:'Proposal List',
	GovProposalsProposalDetails:'Proposal Details',
	GovGovTxs:'Gov Txs List',
	StatsIRISRichList:'IRIS Rich List',
	StatsIRISRichListAddress:'Address',
	StatsIRISStats:'IRIS Stats Analyse',
}
